### ISSUE TITLE
Questions are not fetched in production

### ISSUE THREAD

**Issue by Nurou** [Devops-ohtuprojekti/DevOpsCSAOS#195]
- production database is in correct shape, but backend seems to not form a connection with it

What we tried:
- local testing -> everything works
- unable to get connection to remote database (Heroku) from local machine
- checked env variables

Suspicions
- config issue causing backend to not connect to postgres

**Comment by lehtoneo** [comment]
I found a link which has some explanation for the error https://help.heroku.com/DR0TTWWD/seeing-fatal-no-pg_hba-conf-entry-errors-in-postgres
