### ISSUE TITLE
Share summary of results in social media

### ISSUE THREAD

**Issue by Samipu** [Devops-ohtuprojekti/DevOpsCSAOS#263]
#191
Estimate: 13

Linked In, Twitter, Facebook

- [x] Buttons for sharing to Results-page
- [x] Template for the share-posts

Built with react-share:
https://www.npmjs.com/package/react-share

**Comment by Nurou** [comment]
Here's a suggestion for a simple-to-use library: https://github.com/nygardk/react-share
Have used it in the past and it's gotten the job done :)
