### ISSUE TITLE
Frontendiin tilanhallinnan alustus

### ISSUE THREAD

**Issue by lehtoneo** [Devops-ohtuprojekti/DevOpsCSAOS#64]
#30

**Comment by Nurou** [comment]
Zustand kirjasto on otettu käyttöön tilan hallintaan (Context APIa hankalaa käyttää server-side renderöinnin kanssa)

**Comment by Samipu** [comment]
Email ja kysymysten vastaukset talletetaan zustandin avulla sovelluksen sisällä.

**Comment by Samipu** [comment]
Vielä todo ennen kuin Done: riittävä testaus.
